name: Deploy henryreed.ai

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          hosting/package-lock.json
          functions/package-lock.json

    - name: Install root dependencies
      run: npm ci || npm install

    - name: Install hosting dependencies
      run: |
        cd hosting
        npm ci || npm install

    - name: Install functions dependencies
      run: |
        cd functions
        npm ci || npm install

    - name: TypeScript type checking - hosting
      run: |
        cd hosting
        npx tsc --noEmit

    - name: TypeScript type checking - functions
      run: |
        cd functions
        npx tsc --noEmit

    - name: ESLint - hosting
      run: |
        cd hosting
        npm run lint || echo "ESLint warnings exist but not blocking deployment"

    - name: ESLint - functions
      run: |
        cd functions
        npm run lint || echo "ESLint warnings exist but not blocking deployment"

    - name: Build hosting
      run: |
        cd hosting
        npm run build:exp

    - name: Build functions
      run: |
        cd functions
        npm run build

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          hosting/out/
          functions/lib/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          hosting/package-lock.json
          functions/package-lock.json

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts

    - name: Install dependencies
      run: |
        npm ci || npm install
        cd hosting && (npm ci || npm install)
        cd ../functions && (npm ci || npm install)

    - name: Setup Firebase CLI
      run: npm install -g firebase-tools

    - name: Authenticate with Firebase
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HENRYREEDAI }}

    - name: Set Firebase project
      run: firebase use henryreedai

    - name: Deploy to Firebase
      run: |
        # Deploy hosting and functions
        firebase deploy --only hosting,functions
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    - name: Verify deployment
      run: |
        echo "Verifying deployment..."
        curl -f https://henryreedai.web.app || exit 1
        echo "✅ Deployment verification successful!"

  # Comment: Following project rules - code removals are commented out rather than deleted
  # This allows for easy rollback and maintains deployment history
  # rollback:
  #   needs: [test, deploy]
  #   runs-on: ubuntu-latest
  #   if: failure()
  #   steps:
  #   - name: Rollback deployment
  #     run: |
  #       echo "Deployment failed, consider rollback procedures"
  #       # firebase hosting:clone SOURCE_SITE_ID:SOURCE_VERSION_ID TARGET_SITE_ID